-- IT 부캐 찾기 MBTI 테스트 - Supabase 테이블 초기화 스크립트
-- Supabase 대시보드 > SQL Editor 에서 아래 내용을 그대로 실행하세요.
-- (재실행해도 안전하도록 작성되어 있습니다.)

create table if not exists public.mbti_results (
  id bigint generated by default as identity primary key,
  mbti_type text not null,
  answers jsonb not null,
  created_at timestamptz not null default now()
);

-- Row Level Security 활성화
alter table public.mbti_results enable row level security;

-- 기존 정책이 있다면 제거 후 재생성 (재실행 시 충돌 방지)
drop policy if exists "Allow public insert on mbti_results" on public.mbti_results;
drop policy if exists "Allow public read on mbti_results" on public.mbti_results;

-- 누구나(익명 사용자 포함) 테스트 결과를 저장할 수 있도록 허용
create policy "Allow public insert on mbti_results"
  on public.mbti_results
  for insert
  to anon
  with check (true);

-- 누구나 전체 참여자 수를 집계 조회할 수 있도록 허용 (실시간 카운팅 배너용)
create policy "Allow public read on mbti_results"
  on public.mbti_results
  for select
  to anon
  using (true);

-- 메인 화면의 실시간 누적 참여자 수 배너가 동작하도록
-- mbti_results 테이블을 Realtime 발행(publication) 대상에 등록합니다.
do $$
begin
  alter publication supabase_realtime add table public.mbti_results;
exception
  when duplicate_object then
    null; -- 이미 등록되어 있으면 무시
end $$;
