-- IT 부캐 찾기 MBTI 테스트 - Supabase 테이블 스키마
-- Supabase 대시보드 > SQL Editor 에서 아래 내용을 실행하세요.

create table if not exists public.mbti_results (
  id bigint generated by default as identity primary key,
  mbti_type text not null,
  answers jsonb not null,
  created_at timestamptz not null default now()
);

-- Row Level Security 활성화
alter table public.mbti_results enable row level security;

-- 누구나(익명 사용자 포함) 결과를 저장할 수 있도록 허용
create policy "Allow public insert on mbti_results"
  on public.mbti_results
  for insert
  to anon
  with check (true);

-- 누구나 전체 참여자 수를 집계 조회할 수 있도록 허용 (실시간 카운팅 배너용)
create policy "Allow public read on mbti_results"
  on public.mbti_results
  for select
  to anon
  using (true);

-- 참고: 홈 화면의 실시간 카운터(Realtime)가 동작하려면
-- Supabase 대시보드 > Database > Replication 메뉴에서
-- mbti_results 테이블의 Realtime 토글을 켜주세요.
